### ISSUE TITLE
GPG error & packages not available

### ISSUE THREAD

**Issue by mAPBhlJ** [CoRfr/docker-ssacli#1]
When attempting to build the docker image, I get the following GPG erro

`W: GPG error: http://downloads.linux.HPE.com jessie/current Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C208ADDE26C2B797`

I can work around this using:

`echo "deb [trusted=yes] http://downloads.linu...` but we'd rather fix the actual issue.

**Comment by mAPBhlJ** [comment]
Also, when attempting to build the dockerfile I get the following:

Package hpssacli is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  ssacli

It appears both hpacucli and hpssacli are obsolete and no longer available on these repos.

We should change the last part of the last run command to:

apt-get install -y ssacli \

**Comment by CoRfr** [comment]
Thanks @Paul-Ver , I guess we can close this issue since it was fixed by your PR.
I'm trying to create a repository `corfr/ssacli` on GitHub as I didn't want to break the interface for existing image.
